name: Generate Snake

on:
  schedule:
      # run every 12 hours
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          # Use your username directly or repository owner
          github_user_name: telomelonia
          # Output files directly to the root
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark
            github-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      # Commit and push changes to main branch
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add github-snake.svg
          git add github-snake-dark.svg
          git add github-snake.gif
          git commit -m "Generate Snake Animation"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
